version: 2.1

jobs:

  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install & Cache Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Audit Dependencies
          command: npm audit
      - run:
          name: Lint Code
          command: npm run lint
      - run:
          image: circleci/node:latest-browsers
          name: Run Tests
          command: npm run test

  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  cicd:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master